name: Release to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 4" # Weekly Thursday at 3am UTC (standardized)

permissions:
  contents: read # This is required for actions/checkout

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: frasermolyneux/actions/dotnet-ci@main
      with:
        dotnet-version: 9.0.x
        src-folder: "src"
        majorMinorVersion: "1.1"

  publish-nuget-packages:
    environment: NuGet
    runs-on: ubuntu-latest
    needs: [dotnet-ci]

    steps:
    - uses: actions/checkout@v5

    - uses: frasermolyneux/actions/publish-nuget-packages@main
      with:
        artifact-name: "nuget-packages"
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
