name: Release to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 1" # Every Monday at 3am

permissions:
  contents: read # This is required for actions/checkout

concurrency: # This is required to prevent multiple runs of the same workflow from running at the same time.
  group: ${{ github.workflow }}

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: frasermolyneux/actions/dotnet-ci@main
      with:
        dotnet-version: 7.0.x
        src-folder: "src"
        majorMinorVersion: "1.1"

  publish-nuget-packages:
    environment: NuGet
    runs-on: ubuntu-latest
    needs: [dotnet-ci]

    steps:
    - uses: actions/checkout@v3

    - uses: frasermolyneux/actions/publish-nuget-packages@main
      with:
        artifact-name: "nuget-packages"
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
